# Generated by Django 6.0.3 on 2026-03-25 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProjeto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_evento', models.DateTimeField()),
                ('vagas_limite', models.PositiveIntegerField(default=20)),
                ('ativo', models.BooleanField(default=True)),
                ('vagas_por_setor', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['data_evento'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('vagas_limite', models.PositiveIntegerField(default=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='inscricao',
            name='unique_inscricao_por_colaborador_e_acao',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.dataprojeto'),
        ),
        migrations.AddField(
            model_name='dataprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='core.projeto'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.projeto'),
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('projeto', 'colaborador'), name='unique_inscricao_por_colaborador_e_projeto'),
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='acao',
        ),
    ]
