# Generated by Django 6.0.3 on 2026-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataprojeto_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
