# Generated by Django 6.0.3 on 2026-03-26 11:40

from django.db import migrations, models


def normalizar_cpfs_duplicados(apps, schema_editor):
    Colaborador = apps.get_model("core", "Colaborador")
    usados = set()

    for colab in Colaborador.objects.all().order_by("created_at", "id"):
        cpf_atual = (colab.cpf or "").strip()
        if not cpf_atual:
            cpf_atual = "000.000.000-00"

        if cpf_atual not in usados:
            usados.add(cpf_atual)
            if colab.cpf != cpf_atual:
                colab.cpf = cpf_atual
                colab.save(update_fields=["cpf"])
            continue

        # Gera um CPF técnico único para evitar erro ao criar índice unique.
        sufixo = str(colab.id).replace("-", "")[-6:]
        cpf_novo = f"999.99{sufixo[:2]}.{sufixo[2:5]}-{sufixo[5:]}"
        while cpf_novo in usados:
            cpf_novo = f"998.99{sufixo[:2]}.{sufixo[2:5]}-{sufixo[5:]}"
        colab.cpf = cpf_novo
        colab.save(update_fields=["cpf"])
        usados.add(cpf_novo)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_colaborador_required_fields_remove_whatsapp'),
    ]

    operations = [
        migrations.RunPython(normalizar_cpfs_duplicados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
