# Generated by Django 6.0.3 on 2026-03-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sync_sede_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
